### ISSUE TITLE
Validate DEC for Antares between -80 and 50

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-antares#10]

**Comment by volodymyrss** [comment]
instrument-specific validation on common parameters can be done by dispatcher plugin.

**Comment by dsavchenko** [comment]
It now returns the exception, which is even informative in the frontend 
![image](https://user-images.githubusercontent.com/56398430/117684687-e55dd800-b1bd-11eb-94d2-9605c04fecb1.png)
But still is a bit ugly
User-side pre-validation would be beneficial
Not for immediate action in this release, anyway, I think

PS. Alternatively, this could be about what we discussed, as dispatcher may propose the right ranges etc.

**Comment by volodymyrss** [comment]
yes, this https://github.com/oda-hub/dispatcher-app/issues/38
but way later.

**Comment by dsavchenko** [comment]
It is validated on the dispatcher level. The error is returned for the wrong values. I propose to close
