### ISSUE TITLE
Include also actual plotted UL in fits file

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/dispatcher-plugin-antares#11]
Currently only UL(gamma) is there, but ~flux(E) is plotted. Include it in fits also

**Comment by volodymyrss** [comment]
So you do it yourself, yes?

**Comment by dsavchenko** [comment]
Yes, I will do it. This one is for the future after release, of course

**Comment by volodymyrss** [comment]
Ok, just to confirm!

**Comment by volodymyrss** [comment]
stale? @dsavchenko

**Comment by dsavchenko** [comment]
It is actually resolved
