### ISSUE TITLE
starting from baseline, implement few real tests, for unit testng and integration

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-antares#6]
* there could be there is some meaningful dummy-like query?
* we could install it as a requirement and test it with a another fixture. If it is possible.
* if not possible, the tests should be really considered an "integration", in sense that it will be run on a specific instance, deployed for review.
  * I.e. it will not work with github actions.
  * In this case, the backend access will be configured on defining the test.
  * You can test it while setting your own instance.
  * And we test it after deploying in unige and also regularly.

**Comment by volodymyrss** [comment]
please see @dsavchenko if this agrees with follow-up of #4 and #3

**Comment by dsavchenko** [comment]
Implemented in #8 I think
