### ISSUE TITLE
change affiliations in readme?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-antares#7]
do we need to? And maybe also in source?
Since #4 brought it up, but was approved and closed.

**Comment by volodymyrss** [comment]
if it was done already to your needs feel free to close of course.

**Comment by dsavchenko** [comment]
> if it was done already to your needs feel free to close of course.

Not at all. Maybe, it is a bit political question
I almost didn't edit READMEs yet

**Comment by volodymyrss** [comment]
We had a [discussion with Andrea about something related](https://github.com/andreatramacere/oda_api/issues/5).

Maybe it is also useful to consider some agreed code of conduct, [including conventions for attribution](https://github.com/oda-hub/code-of-conduct-for-developers/blob/main/README.md). And feel free to pose questions or propose changes!

Most of all, code provenance can be reasonably tracked in git, and chosen license defines further reuse and some attribution

And if you are talking only about to which institutes you belong, you could even just put a placeholder reference to your github account.

**Comment by volodymyrss** [comment]
stale @dsavchenko ?

**Comment by dsavchenko** [comment]
Let's close. at least here in the Antares context
